### ISSUE TITLE
Error During Search

### ISSUE THREAD

**Issue by ryan-clancy** [osirrc/irc-centre2019-docker#1]
When running `python run.py search --repo osirrc2019/irc-centre2019 --collection core17 --topic topics/topics.core17.txt --qrels qrels/qrels.core17.txt --output /tmp/ielab` I get the following error:

```
ryan@desktop ~/sync/git/jig [master]× $ python run.py search --repo osirrc2019/irc-centre2019 --collection core17 --topic topics/topics.core17.txt --qrels qrels/qrels.core17.txt --output /tmp/ielab                                                          [20:42:35]
Starting container from saved image...
Logs for search in container with ID 825568bf51b9aa7870ea1037edb6daa97d75d5afb5109a364ff238026ab0bcf6...
Start ranking for WCRobust04
Processing topic 1 of 50
Training of model...
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
Perform predictions on corpus...
0it [00:00, ?it/s]
Predictions on corpus took  0.004494905471801758  seconds.
Producing run...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/work/replicability/run/rank.py", line 48, in <module>
    main()
  File "/work/replicability/run/rank.py", line 33, in main
    rank.rank(file['score_times_robust04'], topic, path['single_runs'])
  File "/work/core/ranking.py", line 26, in rank
    doc_and_score = sorted_dict.popitem()
KeyError: 'dictionary is empty'
Evaluating results using trec_eval...
```

I also get these errors during `prepare` (for more than just the the la times):
```
Missing document with id:  LA120789-0219
Missing document with id:  LA120989-0055
Missing document with id:  LA121089-0047
Missing document with id:  LA121089-0085
Missing document with id:  LA121089-0192
```

Are you able to take a look, @breuert ?

**Comment by breuert** [comment]
Hey @r-clancy,
I think this issue can be traced back to the indexing step and might be related to data extraction. 
Thank you for reporting the errors from `prepare`. I think the required documents from Robust04 won't be indexed.

How to provide the corpora in the mounted volumes?

Our implementation expects the following input.

For Robust04 we copied the files from the original CD-ROMs of TREC Disk 4 & 5. 
So we expect the files to be provided like:

path/to/robust04/
&nbsp;fbis/
&nbsp;&nbsp;fb396001.z
&nbsp;&nbsp;...
&nbsp;fr94/
&nbsp;&nbsp;01/
&nbsp;&nbsp;&nbsp;fr940104.0z
&nbsp;&nbsp;&nbsp;...
&nbsp;&nbsp;...
&nbsp;ft/
&nbsp;&nbsp;ft911/
&nbsp;&nbsp;&nbsp;ft911_1.z
&nbsp;&nbsp;&nbsp;...
&nbsp;&nbsp;...
&nbsp;latimes/
&nbsp;&nbsp;la010189.z
&nbsp;&nbsp;...

We found uncompressed folders of fbis/, fr94/, ft/, and latimes/ on CD.
However, [here](https://github.com/osirrc/jig/issues/28) it is mentioned that Robust04 is provided as fbis.gz fr.gz ft.gz latimes.gz. 
Is Robust04 supposed to be provided this way?
If so, we have to add this to our indexing step.

With regards to NYT our system expects a directory with subfolders by names of years from 1987 to 2007, containing .tgz files.

Robust05 is supposed to contain three folders with subfolders named after years, containing .gz files.

Is there an overview of how the corpora input has to be provided?

**Comment by ryan-clancy** [comment]
@breuert Take a look at https://github.com/osirrc/jig/pull/94 - I'm adding the tree structure and md5 hashes of all of the files to the repo.

**Comment by ryan-clancy** [comment]
Just tried running it again and it seems to work fine... I think I might have pointed to the individual `disk4` and `disk5` directories before for `robust04` and `robust05`, whereas this time I pointed to the root directory.
